import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { isAuthenticated } from "@/lib/services/authService";
import { logoutAction } from "@/lib/actions/authActions";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loggedIn = await isAuthenticated();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <nav>
            <li>
              <Link href="/">Home</Link>
            </li>
            {!loggedIn && (
              <>
                <li>
                  <Link href="/login">Login</Link>
                </li>
                <li>
                  {" "}
                  <Link href="/register">Register</Link>
                </li>
              </>
            )}
            {loggedIn && (
              <>
                <li>Welcome, you are logged in!</li>
                <li>
                  <button onClick={logoutAction}>Logout</button>
                </li>
              </>
            )}
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
